std_msgs/Header header

# Требуемое состояние габаритных огней {True, False}
bool lights_side

# Требуемое состояние фонарей головного света {True, False}
bool lights_head

# Требуемое состояние левого указателя поворота {True, False}
bool lights_left_turn

# Требуемое состояние правого указателя поворота {True, False}
bool lights_right_turn

# Требуемое состояние звукового сигнала {True, False}
bool sound_signal