// Generated by gencpp from file coord_transform/coords.msg
// DO NOT EDIT!


#ifndef COORD_TRANSFORM_MESSAGE_COORDS_H
#define COORD_TRANSFORM_MESSAGE_COORDS_H

#include <ros/service_traits.h>


#include <coord_transform/coordsRequest.h>
#include <coord_transform/coordsResponse.h>


namespace coord_transform
{

struct coords
{

typedef coordsRequest Request;
typedef coordsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct coords
} // namespace coord_transform


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::coord_transform::coords > {
  static const char* value()
  {
    return "5506dc073028d0e0a02766c42314c146";
  }

  static const char* value(const ::coord_transform::coords&) { return value(); }
};

template<>
struct DataType< ::coord_transform::coords > {
  static const char* value()
  {
    return "coord_transform/coords";
  }

  static const char* value(const ::coord_transform::coords&) { return value(); }
};


// service_traits::MD5Sum< ::coord_transform::coordsRequest> should match
// service_traits::MD5Sum< ::coord_transform::coords >
template<>
struct MD5Sum< ::coord_transform::coordsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::coord_transform::coords >::value();
  }
  static const char* value(const ::coord_transform::coordsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::coord_transform::coordsRequest> should match
// service_traits::DataType< ::coord_transform::coords >
template<>
struct DataType< ::coord_transform::coordsRequest>
{
  static const char* value()
  {
    return DataType< ::coord_transform::coords >::value();
  }
  static const char* value(const ::coord_transform::coordsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::coord_transform::coordsResponse> should match
// service_traits::MD5Sum< ::coord_transform::coords >
template<>
struct MD5Sum< ::coord_transform::coordsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::coord_transform::coords >::value();
  }
  static const char* value(const ::coord_transform::coordsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::coord_transform::coordsResponse> should match
// service_traits::DataType< ::coord_transform::coords >
template<>
struct DataType< ::coord_transform::coordsResponse>
{
  static const char* value()
  {
    return DataType< ::coord_transform::coords >::value();
  }
  static const char* value(const ::coord_transform::coordsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COORD_TRANSFORM_MESSAGE_COORDS_H
