// Generated by gencpp from file coord_transform/coordsResponse.msg
// DO NOT EDIT!


#ifndef COORD_TRANSFORM_MESSAGE_COORDSRESPONSE_H
#define COORD_TRANSFORM_MESSAGE_COORDSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace coord_transform
{
template <class ContainerAllocator>
struct coordsResponse_
{
  typedef coordsResponse_<ContainerAllocator> Type;

  coordsResponse_()
    : output()  {
    }
  coordsResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::coord_transform::coordsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coord_transform::coordsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct coordsResponse_

typedef ::coord_transform::coordsResponse_<std::allocator<void> > coordsResponse;

typedef boost::shared_ptr< ::coord_transform::coordsResponse > coordsResponsePtr;
typedef boost::shared_ptr< ::coord_transform::coordsResponse const> coordsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coord_transform::coordsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coord_transform::coordsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::coord_transform::coordsResponse_<ContainerAllocator1> & lhs, const ::coord_transform::coordsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::coord_transform::coordsResponse_<ContainerAllocator1> & lhs, const ::coord_transform::coordsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace coord_transform

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::coord_transform::coordsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coord_transform::coordsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coord_transform::coordsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coord_transform::coordsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coord_transform::coordsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coord_transform::coordsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coord_transform::coordsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5a4ac2a55e91a597647da3a0f20a3e1";
  }

  static const char* value(const ::coord_transform::coordsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5a4ac2a55e91a59ULL;
  static const uint64_t static_value2 = 0x7647da3a0f20a3e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::coord_transform::coordsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coord_transform/coordsResponse";
  }

  static const char* value(const ::coord_transform::coordsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coord_transform::coordsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose output\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::coord_transform::coordsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coord_transform::coordsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coordsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coord_transform::coordsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coord_transform::coordsResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COORD_TRANSFORM_MESSAGE_COORDSRESPONSE_H
